### ISSUE TITLE
[Removing headers on button columns in Teacher's lectures page]

### ISSUE THREAD

**Issue by Nino-n** [Bylom/PULSeBS-T16#5]
It could be better if the header is removed from the column and embedded in the button so if the list of lectures is long, while swiping down the pages I continue to see the full meaning of the button and i don't have to return up to read the headers.
Thank you :)

**Comment by AndreaBruno97** [comment]
Issue solved: we removed the headers for the buttons, and renamed the labels in the buttons accordingly
